import React, { useState } from 'react';
import {
  X,
  AlertTriangle,
  Download,
  RotateCcw,
  Sparkles,
  Info,
  ShieldAlert,
  CheckCircle2,
  Bot,
  Loader2,
  AlertCircle,
} from 'lucide-react';
import type { DiseaseDetectionResult } from '../../services/diseaseDetectionService';
import { fetchGeminiDiseaseExplanation } from '../../services/geminiService';

interface DetectionResultModalProps {
  result: DiseaseDetectionResult;
  imageUrl: string;
  onClose: () => void;
  onReset: () => void;
}

export const DetectionResultModal: React.FC<DetectionResultModalProps> = ({
  result,
  imageUrl,
  onClose,
  onReset,
}) => {
  const isHealthy = result.severity === 'Healthy';

  const [geminiExplanation, setGeminiExplanation] = useState<string | null>(null);
  const [geminiLoading, setGeminiLoading] = useState(false);
  const [geminiError, setGeminiError] = useState<string | null>(null);

  const handleFetchGeminiAdvice = async () => {
    setGeminiLoading(true);
    setGeminiError(null);
    try {
      const res = await fetchGeminiDiseaseExplanation({
        crop: result.crop,
        disease: result.disease,
        severity: result.severity,
        symptoms: result.symptoms,
        causes: result.causes,
      });

      if (res.success && res.explanation) {
        setGeminiExplanation(res.explanation);
      } else {
        setGeminiError(res.error || 'Gemini API is unavailable or quota limit reached.');
      }
    } catch {
      setGeminiError('Failed to connect to backend Gemini AI service.');
    } finally {
      setGeminiLoading(false);
    }
  };

  const handleDownloadReport = () => {
    const reportText = `=====================================================
AGRIVISION AI — REAL BOTANICAL PATHOLOGY REPORT
=====================================================
Analyzed At: ${result.analyzedAt}
Crop: ${result.crop}
Diagnosis: ${result.disease}
Scientific Name: ${result.scientificName}
Diagnostic Confidence: ${result.confidence}%
Severity Index: ${result.severity}

SYMPTOMS IDENTIFIED:
${result.symptoms.map((s) => `- ${s}`).join('\n')}

CAUSES & FAVORABLE CONDITIONS:
${result.causes.map((c) => `- ${c}`).join('\n')}

ORGANIC & BIOLOGICAL CONTROL:
${result.treatments.organic.map((t) => `- ${t}`).join('\n')}

CHEMICAL MANAGEMENT (IF SEVERE):
${result.treatments.chemical.map((t) => `- ${t}`).join('\n')}

PREVENTIVE MEASURES:
${result.treatments.preventive.map((p) => `- ${p}`).join('\n')}
=====================================================
Report generated by AgriVision AI Verified Diagnostic Engine
=====================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AgriVision_${result.crop}_${result.disease.replace(/\s+/g, '_')}_Report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in">
      <div className="bg-white w-full max-w-2xl rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/80">
          <div className="flex items-center gap-2.5">
            <div className={`w-8 h-8 rounded-xl flex items-center justify-center ${isHealthy ? 'bg-emerald-100 text-emerald-800' : 'bg-emerald-100 text-[#15803D]'}`}>
              <Sparkles className="w-4 h-4 stroke-[2.2]" />
            </div>
            <div>
              <h3 className="text-base font-bold text-[#0F172A] leading-tight">
                AI Diagnostic Report
              </h3>
              <span className="text-[11px] text-slate-500 font-medium">
                Analysis completed at {result.analyzedAt}
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-700 hover:bg-slate-200/60 rounded-full transition-colors cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-5">
          {/* Top Summary Card with Image & Core Metrics */}
          <div className="bg-[#F8FAFC] border border-slate-200 rounded-xl p-4 flex flex-col sm:flex-row items-center gap-4">
            {/* Scanned Leaf Thumbnail with AI Scan Reticle */}
            <div className="relative w-28 h-28 rounded-xl overflow-hidden shrink-0 border border-slate-300 shadow-xs">
              <img
                src={imageUrl}
                alt="Analyzed Leaf"
                className="w-full h-full object-cover"
              />
              <div className="absolute inset-2 border-2 border-[#22C55E] rounded-md shadow-[0_0_8px_#22C55E] pointer-events-none" />
              <div className="absolute top-1 right-1 bg-black/70 px-1.5 py-0.5 rounded text-[9px] font-bold text-emerald-400">
                AI SCAN
              </div>
            </div>

            {/* Disease Identity */}
            <div className="flex-1 text-center sm:text-left space-y-1">
              <div className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10.5px] font-bold uppercase tracking-wider border ${
                isHealthy
                  ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                  : 'bg-rose-50 text-rose-700 border border-rose-200'
              }`}>
                {isHealthy ? (
                  <>
                    <CheckCircle2 className="w-3 h-3 text-emerald-600 shrink-0" />
                    <span>Healthy Foliage</span>
                  </>
                ) : (
                  <>
                    <AlertTriangle className="w-3 h-3 text-rose-500 shrink-0" />
                    <span>Pathology Detected ({result.severity} Severity)</span>
                  </>
                )}
              </div>
              <h4 className="text-xl font-extrabold text-[#0F172A] leading-snug">
                {result.disease}
              </h4>
              <p className="text-xs text-slate-500 italic">
                {result.scientificName} • Crop: <span className="font-semibold text-slate-700">{result.crop}</span>
              </p>

              {/* Confidence Meter */}
              <div className="pt-2 flex items-center gap-3">
                <div className="flex-1 bg-slate-200 h-2 rounded-full overflow-hidden">
                  <div
                    className="bg-[#15803D] h-full rounded-full transition-all duration-500"
                    style={{ width: `${result.confidence}%` }}
                  />
                </div>
                <span className="text-xs font-bold text-emerald-800">
                  {result.confidence}% Confidence
                </span>
              </div>
            </div>
          </div>

          {/* Description */}
          <div className="text-xs text-slate-700 leading-relaxed bg-emerald-50/40 p-3.5 rounded-xl border border-emerald-100">
            <p>
              {result.summary ||
                `${result.disease} was identified on ${result.crop} with ${result.confidence}% visual diagnostic confidence. Severity index: ${result.severity}.`}
            </p>
          </div>

          {/* Symptoms & Causes Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="border border-slate-200 rounded-xl p-3.5 space-y-2">
              <h5 className="text-xs font-bold text-[#0F172A] flex items-center gap-1.5">
                <ShieldAlert className="w-3.5 h-3.5 text-amber-600" />
                <span>Identified Symptoms</span>
              </h5>
              <ul className="text-[11.5px] text-slate-600 space-y-1 list-disc list-inside">
                {(result.symptoms || []).map((s, idx) => (
                  <li key={idx}>{s}</li>
                ))}
              </ul>
            </div>

            <div className="border border-slate-200 rounded-xl p-3.5 space-y-2">
              <h5 className="text-xs font-bold text-[#0F172A] flex items-center gap-1.5">
                <Info className="w-3.5 h-3.5 text-blue-600" />
                <span>Favorable Conditions & Causes</span>
              </h5>
              <ul className="text-[11.5px] text-slate-600 space-y-1 list-disc list-inside">
                {(result.causes || []).map((c, idx) => (
                  <li key={idx}>{c}</li>
                ))}
              </ul>
            </div>
          </div>

          {/* Actionable Treatment Plan */}
          <div className="border border-slate-200 rounded-xl p-4 space-y-3">
            <h5 className="text-xs font-bold text-[#0F172A] uppercase tracking-wider">
              Recommended Management Plan
            </h5>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                <span className="text-[11px] font-bold text-emerald-800 block mb-1">
                  🌿 Organic / Biological Control
                </span>
                <ul className="text-[11px] text-slate-600 space-y-1">
                  {(result.treatments?.organic || []).map((t, idx) => (
                    <li key={idx}>• {t}</li>
                  ))}
                </ul>
              </div>

              <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
                <span className="text-[11px] font-bold text-slate-800 block mb-1">
                  🧪 Chemical Management
                </span>
                <ul className="text-[11px] text-slate-600 space-y-1">
                  {(result.treatments?.chemical || []).map((t, idx) => (
                    <li key={idx}>• {t}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Google Gemini AI Agronomist Advisory Section */}
          <div className="border border-emerald-200 bg-emerald-50/40 rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-7 h-7 rounded-lg bg-[#15803D] text-white flex items-center justify-center">
                  <Bot className="w-4 h-4" />
                </div>
                <div>
                  <h5 className="text-xs font-bold text-[#0F172A] flex items-center gap-1.5">
                    <span>Google Gemini AI Agronomist Advisory</span>
                    <span className="px-1.5 py-0.5 rounded text-[9.5px] font-extrabold bg-emerald-100 text-emerald-800 border border-emerald-200">
                      AI GENERATED
                    </span>
                  </h5>
                  <p className="text-[10.5px] text-slate-500 font-medium">Deep AI pathology insight & localized field action</p>
                </div>
              </div>

              {!geminiExplanation && !geminiLoading && (
                <button
                  type="button"
                  onClick={handleFetchGeminiAdvice}
                  className="px-3 py-1.5 text-xs font-bold text-white bg-[#15803D] hover:bg-[#166534] rounded-lg shadow-xs transition-all flex items-center gap-1.5 cursor-pointer"
                >
                  <Sparkles className="w-3.5 h-3.5 text-amber-300" />
                  <span>Get Gemini Advice</span>
                </button>
              )}
            </div>

            {geminiLoading && (
              <div className="p-3 bg-white rounded-lg border border-slate-200 flex items-center gap-2 text-xs text-slate-600 font-medium">
                <Loader2 className="w-4 h-4 text-[#15803D] animate-spin" />
                <span>Generating tailored agronomic advice via Google Gemini API...</span>
              </div>
            )}

            {geminiError && (
              <div className="p-3 rounded-lg bg-rose-50 border border-rose-200 text-rose-700 text-xs font-medium flex items-start gap-2">
                <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
                <div>
                  <span className="font-bold block text-rose-800">Gemini AI Notice:</span>
                  <span>{geminiError}</span>
                </div>
              </div>
            )}

            {geminiExplanation && (
              <div className="p-3.5 bg-white rounded-lg border border-emerald-200 text-xs text-slate-800 leading-relaxed space-y-2 animate-in fade-in">
                <div className="whitespace-pre-wrap">{geminiExplanation}</div>
                <div className="pt-2 border-t border-slate-100 text-[10px] text-slate-400 font-semibold flex items-center justify-between">
                  <span>Generative AI analysis by Google Gemini</span>
                  <button
                    type="button"
                    onClick={handleFetchGeminiAdvice}
                    className="text-[#15803D] hover:underline cursor-pointer"
                  >
                    Refresh Advice
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Modal Footer Actions */}
        <div className="px-6 py-3.5 bg-slate-50 border-t border-slate-100 flex items-center justify-between">
          <button
            type="button"
            onClick={onReset}
            className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-slate-700 bg-white hover:bg-slate-100 border border-slate-300 rounded-lg transition-colors cursor-pointer"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>Scan Another Leaf</span>
          </button>

          <button
            type="button"
            onClick={handleDownloadReport}
            className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-white bg-[#15803D] hover:bg-[#166534] rounded-lg transition-colors shadow-xs cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Report</span>
          </button>
        </div>
      </div>
    </div>
  );
};
